### ISSUE TITLE
New ranks manual

### ISSUE THREAD

**Issue by Crypt97** [DeathEnderMan/Nautical-Ranks#8]
And can I add my own ranks to the Bedrock section? Because no matter how I looked, I couldn't figure out how it worked.

**Comment by ElliotVamp** [comment]
From what i found out you can just open something like Photoshop and edit the texture and edit a rank, no clue how to add new ones though, only know on Java  which is basically edit an existing rank, save it as a new image instead of replacing, search up special new characters that nobody would use, for example Æ since not many would have that on their keyboard let alone use it on an english server then you're basically  done.

**Comment by ashwaniimpact** [comment]
if you make a new ranks to the packs you can use this https://inkiralet.github.io/libglyph-mcbe/ 
NOT MINE

**Comment by DeathEnderMan** [comment]
> From what i found out you can just open something like Photoshop and edit the texture and edit a rank, no clue how to add new ones though, only know on Java which is basically edit an existing rank, save it as a new image instead of replacing, search up special new characters that nobody would use, for example Æ since not many would have that on their keyboard let alone use it on an english server then you're basically done.

Hi we use bedrock emojis to make the link you can find all the symbols at https://wiki.bedrock.dev/concepts/emojis.html

**Comment by DrPanayioths** [comment]
Video To Help You Make Your Own Rank: https://www.youtube.com/watch?v=7c0fId3OguI&t=638s
